version: '3.8'

services:
  # Test Database
  test_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: callback_listener_test
      POSTGRES_USER: callback_user
      POSTGRES_PASSWORD: callback_pass
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U callback_user -d callback_listener_test"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Test Runner
  test:
    build: .
    environment:
      FLASK_ENV: testing
      TEST_DATABASE_URL: postgresql://callback_user:callback_pass@test_db:5432/callback_listener_test
      SECRET_KEY: test-secret-key
    depends_on:
      test_db:
        condition: service_healthy
    command: >
      sh -c "
        flask db upgrade &&
        pytest -v --cov=app --cov-report=html --cov-report=term-missing
      "
    volumes:
      - .:/app
      - ./htmlcov:/app/htmlcov
