name: Development Docker Build and Push

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to CloudKeter Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.KETER_REGISTRY_URL }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push multi-arch image (amd64, arm64)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ vars.KETER_REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:dev
          platforms: linux/amd64,linux/arm64
